FROM oven/bun:1.1 AS build
WORKDIR /app
COPY client/package.json client/bun.lockb* ./
RUN bun install
COPY client ./
RUN bun run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY client/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
